services:
  web-app:
    build:
      context: .
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - './service:/service'
    environment:
      - DB_HOST=db
      - DB_NAME=db_service
      - DB_USER=admin
      - DB_PASS=admin

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=db_service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    container_name: pgdb
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: null