# Generated by Django 4.2.6 on 2023-10-26 17:39

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman_user',
            name='name',
        ),
        migrations.AlterField(
            model_name='sportsman_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='sportsman_user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sportsman_user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Подтверждение почты пользователя. Только после этого предоставляется полноценный доступ к ресурсу', verbose_name='Подтверждение пользователя'),
        ),
        migrations.AlterField(
            model_name='sportsman_user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='sportsman_user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким никнеймом уже существует'}, help_text='Требования: меньше 100 символов, Буквы, цифры и @/./+/-/_ ТОЛЬКО.', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
