# Generated by Django 4.2.6 on 2023-10-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_alter_sportsman_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sportsman_user',
            managers=[
            ],
        ),
    ]
