# Generated by Django 4.2.6 on 2023-10-26 17:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_remove_sportsman_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman_user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким никнеймом уже существует'}, help_text='Требования: меньше 100 символов, Буквы, цифры и @/./+/-/_ ТОЛЬКО.', max_length=100, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
