# Generated by Django 4.2.6 on 2023-10-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0003_alter_sportsman_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsman_user',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
