# Generated by Django 4.2.6 on 2023-10-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0003_alter_sportsman_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sportsman_user',
            managers=[
            ],
        ),
    ]
