# Generated by Django 4.2.6 on 2023-10-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_fields', models.CharField(choices=[('3 юношеский', 'Третий юношеский спортивный разряд'), ('2 юношеский', 'Второй юношеский спортивный разряд'), ('1 юношеский', 'Первый юношеский спортивный разряд'), ('3 спортивный', 'Третий спортивный разряд'), ('2 спортивный', 'Второй спортивный разряд'), ('1 спортивный', 'Первый спортивный разряд'), ('КМС', 'Кандидат в мастера спорта'), ('МС', 'Мастер спорта'), ('МСМК', 'мастер спорта России международного класса')])),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sport_categories.sport')),
            ],
        ),
    ]
