# Generated by Django 4.2.6 on 2023-11-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='sport_categories.sport'),
        ),
        migrations.AlterField(
            model_name='rankforexercise',
            name='exercise_standart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranks', to='sport_categories.exercise'),
        ),
    ]
