# Generated by Django 4.2.6 on 2023-10-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_categories', '0002_remove_exercise_rank_fields_exercise_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='measurement_system',
            field=models.CharField(default='kg', max_length=50),
            preserve_default=False,
        ),
    ]
