# Generated by Django 4.2.6 on 2023-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_categories', '0003_sport_measurement_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standartexercise',
            name='standart_mark',
            field=models.FloatField(),
        ),
    ]
